CREATE TABLE TBLUSERTYPE(
	USERTYPEID INT PRIMARY KEY,
	USERTYPENAME TEXT,
	VIEWABLE BOOLEAN,			-- Viewing stricted post
	COMMENTABLE BOOLEAN,	-- Commenting on a post
	POSTABLE BOOLEAN,			-- Posting new post
	DELETEABLE BOOLEAN,		-- Deleting other's post
	USERABLE BOOLEAN			-- User assigning permission
);

CREATE TABLE TBLUSER(
	USERID INT PRIMARY KEY,
	EMAIL TEXT UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	USERNAME TEXT,
	GENDER TEXT,
	DATEOFBIRTH DATE,
	PHONENUMBER TEXT,
	REGISTERDATE TIMESTAMP,
	USERIMAGEURL TEXT,
	USERTYPEID INT REFERENCES TBLUSERTYPE(USERTYPEID)
);

CREATE TABLE TBLCATEGORY(
	CATEGORYID INT PRIMARY KEY,
	CATEGORYNAME TEXT,
	CATEGORYLOGOURL TEXT
);

CREATE TABLE TBLVIDEO(
	VIDEOID INT PRIMARY KEY,
	VIDEONAME TEXT,
	DESCRIPTION TEXT,
	YOUTUBEURL TEXT,		-- e.g. RFinNxS5KN4
	FILEURL TEXT,
	PUBLICVIEW BOOLEAN,
	POSTDATE TIMESTAMP,
	USERID INT REFERENCES TBLUSER(USERID),
	VIEWCOUNT INT
);

CREATE TABLE TBLCATEGORYVIDEO(
	VIDEOID INT REFERENCES TBLVIDEO(VIDEOID),
	CATEGORYID INT REFERENCES TBLCATEGORY(CATEGORYID),
	CONSTRAINT pk_categoryvideo PRIMARY KEY (VIDEOID, CATEGORYID)
);

CREATE TABLE TBLCOMMENT(
	COMMENTID INT PRIMARY KEY,
	COMMENTDATE TIMESTAMP,
	COMMENTTEXT TEXT,
	VIDEOID INT REFERENCES TBLVIDEO(VIDEOID),
	USERID INT REFERENCES TBLUSER(USERID)
);

CREATE TABLE TBLVOTE(
	USERID INT REFERENCES TBLUSER(USERID),
	VIDEOID INT REFERENCES TBLVIDEO(VIDEOID),
	VOTETYPE INT,	-- +1, -1, 0
	CONSTRAINT pk_vote PRIMARY KEY (USERID, VIDEOID)
);

CREATE TABLE TBLPLAYLIST(
	PLAYLISTID INT PRIMARY KEY,
	PLAYLISTNAME TEXT,
	DESCRIPTION TEXT,
	USERID INT REFERENCES TBLUSER(USERID),
	THUMBNAILURL TEXT,
	PUBLICVIEW BOOLEAN
);

CREATE TABLE TBLPLAYLISTDETAIL(
	PLAYLISTID INT REFERENCES TBLPLAYLIST(PLAYLISTID),
	VIDEOID INT REFERENCES TBLVIDEO(VIDEOID),
	INDEX INT,
	CONSTRAINT pk_playlistdetail PRIMARY KEY (PLAYLISTID, VIDEOID)
);

CREATE TABLE HISTORY(
	HISTORYID INT PRIMARY KEY,
	HISTORYDATE TIMESTAMP,
	USERID INT REFERENCES TBLUSER(USERID),
	VIDEOID INT REFERENCES TBLVIDEO(VIDEOID)
);













